version: '3.8'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  api:
    container_name: api
    hostname: api
    build:
      context: ./Generate_profile_backend/
    volumes:
      - ./Generate_profile_backend:/api
      - bundle_data:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      API_DATABASE_PASSWORD: ${DB_PASSWORD}

  front:
    container_name: front
    hostname: front
    build:
      context: ./Generate_profile_app/
    volumes:
      - ./Generate_profile_app:/front
      - node_modules:/front/node_modules
    ports:
      - 8080:8080
    depends_on:
      - api
    environment:
      - WATCHPACK_POLLING=true
    command: 'yarn dev'

volumes:
  bundle_data:
  postgres:
  node_modules:
